In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
power_data = pd.read_excel('data/시도별_용도별.xls')
print(power_data.shape)

(19, 28)

In [3]:
power_data.head(10) #상위 10개 행 출력!

,구분,주거용,공공용,서비스업,업무용합계,농림어업,광업,제조업,식료품제조,"섬유,의류",...,기타기계,사무기기,전기기기,"영상,음향",자동차,기타운송,가구및기타,재생재료,산업용합계,합계
0,강원,1940933,1400421,6203749,7604170,607139,398287,6002286,546621,13027,...,35063,2019,38062,43986,113448,108629,12872,3418,7007712,16552816
1,개성,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,경기,16587710,5533662,33434551,38968213,2371347,317263,56603327,2544420,2109963,...,3613798,317244,1040171,24519644,2977165,67594,1833112,133041,59291937,114847859
3,경남,4260988,1427560,8667737,10095297,2141813,95989,18053778,932743,346974,...,1902913,8070,924235,534196,2156059,2048646,262523,47662,20291580,34647864
4,경북,3302463,1578115,8487402,10065517,1747462,224568,30115601,566071,3780171,...,782570,14468,750786,4174971,2356890,123935,60280,77104,32087631,45455611
5,광주,1954876,565527,3174973,3740500,74608,2898,2910768,161072,295922,...,198847,5967,236622,723764,512148,5140,13392,16049,2988274,8683649
6,대구,3151904,826396,5470438,6296834,69142,5858,5862633,212626,1057342,...,516493,58446,180189,252662,1381273,68127,41814,33616,5937633,15386372
7,대전,1872890,954681,3955921,4910602,28643,3326,2608343,204171,41687,...,77970,2949,83609,474561,218191,5439,31657,2252,2640312,9423804
8,부산,4473510,1305876,7582169,8888045,107927,25289,7512588,532943,528513,...,904149,4913,107717,90644,1046529,231141,49733,13104,7645804,21007358
9,서울,13131172,3581534,27647345,31228879,15150,4064,1918893,227077,497699,...,163688,4395,11425,46225,20182,17656,132707,2875,1938107,46298158

In [4]:
type(power_data)

pandas.core.frame.DataFrame

In [5]:
power_data.columns

Index(['구분', '주거용', '공공용', '서비스업', '업무용합계', '농림어업', '광업', '제조업', '식료품제조',
       '섬유,의류', '목재,나무', '펄프,종이', '출판,인쇄', '석유,화확', '의료,광학', '요업', '1차금속',
       '조립금속', '기타기계', '사무기기', '전기기기', '영상,음향', '자동차', '기타운송', '가구및기타', '재생재료',
       '산업용합계', '합계'],
      dtype='object')

In [6]:
power_data.values

array([['강원', 1940933, 1400421, 6203749, 7604170, 607139, 398287,
        6002286, 546621, 13027, 19147, 24382, 7727, 175323, 84397,
        3695776, 1038913, 39477, 35063, 2019, 38062, 43986, 113448,
        108629, 12872, 3418, 7007712, 16552816],
       ['개성', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0],
       ['경기', 16587710, 5533662, 33434551, 38968213, 2371347, 317263,
        56603327, 2544420, 2109963, 529274, 1917458, 731348, 6881775,
        1336390, 1728379, 2020196, 2302355, 3613798, 317244, 1040171,
        24519644, 2977165, 67594, 1833112, 133041, 59291937, 114847859],
       ['경남', 4260988, 1427560, 8667737, 10095297, 2141813, 95989,
        18053778, 932743, 346974, 60160, 817685, 28486, 1865583, 178498,
        429920, 3809547, 1699879, 1902913, 8070, 924235, 534196, 2156059,
        2048646, 262523, 47662, 20291580, 34647864],
       ['경북', 3302463, 1578115, 8487402, 10065517, 1747462, 224568,
        30115601, 566071, 3780171, 72680, 361772, 44402, 3653665, 217771,
        1269917, 10874970, 933178, 782570, 14468, 750786, 4174971,
        2356890, 123935, 60280, 77104, 32087631, 45455611],
       ['광주', 1954876, 565527, 3174973, 3740500, 74608, 2898, 2910768,
        161072, 295922, 6782, 41827, 22038, 391151, 27221, 20728, 75702,
        156396, 198847, 5967, 236622, 723764, 512148, 5140, 13392, 16049,
        2988274, 8683649],
       ['대구', 3151904, 826396, 5470438, 6296834, 69142, 5858, 5862633,
        212626, 1057342, 16215, 445646, 46804, 418485, 85871, 68137,
        317580, 661307, 516493, 58446, 180189, 252662, 1381273, 68127,
        41814, 33616, 5937633, 15386372],
       ['대전', 1872890, 954681, 3955921, 4910602, 28643, 3326, 2608343,
        204171, 41687, 4311, 539332, 14802, 630776, 97278, 53481, 56535,
        69342, 77970, 2949, 83609, 474561, 218191, 5439, 31657, 2252,
        2640312, 9423804],
       ['부산', 4473510, 1305876, 7582169, 8888045, 107927, 25289, 7512588,
        532943, 528513, 51980, 27240, 33000, 438833, 74733, 77771,
        2426694, 872952, 904149, 4913, 107717, 90644, 1046529, 231141,
        49733, 13104, 7645804, 21007358],
       ['서울', 13131172, 3581534, 27647345, 31228879, 15150, 4064,
        1918893, 227077, 497699, 4399, 43281, 296772, 286957, 54697,
        26941, 17236, 64682, 163688, 4395, 11425, 46225, 20182, 17656,
        132707, 2875, 1938107, 46298158],
       ['세종', 384903, 299675, 645424, 945099, 69469, 16364, 1502922,
        110211, 70617, 1324, 350896, 2998, 261583, 24557, 305848, 32345,
        11390, 26185, 14319, 33539, 170366, 79009, 0, 5132, 2603,
        1588755, 2918758],
       ['울산', 1487143, 489865, 3649386, 4139251, 80221, 20103, 25883132,
        187738, 943299, 12286, 620457, 3325, 14870740, 22508, 183981,
        4671005, 393469, 169132, 5053, 381602, 24165, 2367150, 1020610,
        4984, 1626, 25983456, 31609850],
       ['인천', 3856852, 921748, 7154416, 8076164, 142953, 71529, 12367816,
        641088, 75895, 639429, 57159, 71120, 2039737, 2250315, 182028,
        2346232, 750654, 942801, 7853, 178502, 1124564, 612898, 54225,
        360778, 32538, 12582298, 24515313],
       ['전남', 2284124, 964024, 5690659, 6654683, 3096126, 73217,
        21453926, 511361, 160506, 27998, 145685, 6714, 13945376, 49380,
        586208, 5036891, 123651, 66431, 1061, 149939, 42399, 72132,
        481592, 14670, 31932, 24623269, 33562076],
       ['전북', 2326183, 1096968, 4910318, 6007286, 1415004, 85300,
        12965875, 1459217, 731651, 291729, 1282937, 10512, 4452120,
        64088, 614013, 2158438, 137635, 159699, 7240, 130692, 420005,
        859741, 70980, 16175, 99003, 14466179, 22799647],
       ['제주', 782601, 301727, 2308732, 2610459, 1364930, 14019, 241537,
        155987, 3497, 1524, 20864, 2436, 19615, 5038, 22521, 993, 3331,
        1167, 0, 771, 0, 773, 532, 1743, 743, 1620486, 5013545],
       ['충남', 2691823, 1089613, 7164439, 8254052, 1928066, 248313,
        37057955, 1137035, 269998, 134109, 809760, 50869, 7787274,
        771894, 914757, 9976454, 565003, 611925, 12208, 428906, 10953811,
        2526658, 33766, 53804, 19725, 39234334, 50180209],
       ['충북', 2027281, 1267140, 4804638, 6071778, 721131, 139856,
        15883448, 1152073, 333846, 51682, 880020, 23940, 2350133, 587361,
        2431846, 469546, 738699, 366871, 23076, 1125141, 4103832, 603349,
        82496, 513501, 46038, 16744435, 24843494],
       ['합계', 64576423, 22204112, 134748546, 156952658, 15373994,
        1347957, 252942540, 10735833, 11247578, 1905882, 8362019,
        1389566, 60293807, 5847599, 8916474, 44290363, 9483924, 10504640,
        487262, 5763846, 47655808, 17790147, 4311878, 3396006, 559909,
        269664491, 491193571]], dtype=object)

In [7]:
power = power_data.set_index('구분'); power

,주거용,공공용,서비스업,업무용합계,농림어업,광업,제조업,식료품제조,"섬유,의류","목재,나무",...,기타기계,사무기기,전기기기,"영상,음향",자동차,기타운송,가구및기타,재생재료,산업용합계,합계
구분,,,,,,,,,,,,,,,,,,,,,
강원,1940933,1400421,6203749,7604170,607139,398287,6002286,546621,13027,19147,...,35063,2019,38062,43986,113448,108629,12872,3418,7007712,16552816
개성,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
경기,16587710,5533662,33434551,38968213,2371347,317263,56603327,2544420,2109963,529274,...,3613798,317244,1040171,24519644,2977165,67594,1833112,133041,59291937,114847859
경남,4260988,1427560,8667737,10095297,2141813,95989,18053778,932743,346974,60160,...,1902913,8070,924235,534196,2156059,2048646,262523,47662,20291580,34647864
경북,3302463,1578115,8487402,10065517,1747462,224568,30115601,566071,3780171,72680,...,782570,14468,750786,4174971,2356890,123935,60280,77104,32087631,45455611
광주,1954876,565527,3174973,3740500,74608,2898,2910768,161072,295922,6782,...,198847,5967,236622,723764,512148,5140,13392,16049,2988274,8683649
대구,3151904,826396,5470438,6296834,69142,5858,5862633,212626,1057342,16215,...,516493,58446,180189,252662,1381273,68127,41814,33616,5937633,15386372
대전,1872890,954681,3955921,4910602,28643,3326,2608343,204171,41687,4311,...,77970,2949,83609,474561,218191,5439,31657,2252,2640312,9423804
부산,4473510,1305876,7582169,8888045,107927,25289,7512588,532943,528513,51980,...,904149,4913,107717,90644,1046529,231141,49733,13104,7645804,21007358
서울,13131172,3581534,27647345,31228879,15150,4064,1918893,227077,497699,4399,...,163688,4395,11425,46225,20182,17656,132707,2875,1938107,46298158
세종,384903,299675,645424,945099,69469,16364,1502922,110211,70617,1324,...,26185,14319,33539,170366,79009,0,5132,2603,1588755,2918758
울산,1487143,489865,3649386,4139251,80221,20103,25883132,187738,943299,12286,...,169132,5053,381602,24165,2367150,1020610,4984,1626,25983456,31609850
인천,3856852,921748,7154416,8076164,142953,71529,12367816,641088,75895,639429,...,942801,7853,178502,1124564,612898,54225,360778,32538,12582298,24515313
전남,2284124,964024,5690659,6654683,3096126,73217,21453926,511361,160506,27998,...,66431,1061,149939,42399,72132,481592,14670,31932,24623269,33562076
전북,2326183,1096968,4910318,6007286,1415004,85300,12965875,1459217,731651,291729,...,159699,7240,130692,420005,859741,70980,16175,99003,14466179,22799647
제주,782601,301727,2308732,2610459,1364930,14019,241537,155987,3497,1524,...,1167,0,771,0,773,532,1743,743,1620486,5013545
충남,2691823,1089613,7164439,8254052,1928066,248313,37057955,1137035,269998,134109,...,611925,12208,428906,10953811,2526658,33766,53804,19725,39234334,50180209
충북,2027281,1267140,4804638,6071778,721131,139856,15883448,1152073,333846,51682,...,366871,23076,1125141,4103832,603349,82496,513501,46038,16744435,24843494
합계,64576423,22204112,134748546,156952658,15373994,1347957,252942540,10735833,11247578,1905882,...,10504640,487262,5763846,47655808,17790147,4311878,3396006,559909,269664491,491193571

In [9]:
power = power.drop(['합계', '개성'], errors='ignore')
power

,주거용,공공용,서비스업,업무용합계,농림어업,광업,제조업,식료품제조,"섬유,의류","목재,나무",...,기타기계,사무기기,전기기기,"영상,음향",자동차,기타운송,가구및기타,재생재료,산업용합계,합계
구분,,,,,,,,,,,,,,,,,,,,,
강원,1940933,1400421,6203749,7604170,607139,398287,6002286,546621,13027,19147,...,35063,2019,38062,43986,113448,108629,12872,3418,7007712,16552816
경기,16587710,5533662,33434551,38968213,2371347,317263,56603327,2544420,2109963,529274,...,3613798,317244,1040171,24519644,2977165,67594,1833112,133041,59291937,114847859
경남,4260988,1427560,8667737,10095297,2141813,95989,18053778,932743,346974,60160,...,1902913,8070,924235,534196,2156059,2048646,262523,47662,20291580,34647864
경북,3302463,1578115,8487402,10065517,1747462,224568,30115601,566071,3780171,72680,...,782570,14468,750786,4174971,2356890,123935,60280,77104,32087631,45455611
광주,1954876,565527,3174973,3740500,74608,2898,2910768,161072,295922,6782,...,198847,5967,236622,723764,512148,5140,13392,16049,2988274,8683649
대구,3151904,826396,5470438,6296834,69142,5858,5862633,212626,1057342,16215,...,516493,58446,180189,252662,1381273,68127,41814,33616,5937633,15386372
대전,1872890,954681,3955921,4910602,28643,3326,2608343,204171,41687,4311,...,77970,2949,83609,474561,218191,5439,31657,2252,2640312,9423804
부산,4473510,1305876,7582169,8888045,107927,25289,7512588,532943,528513,51980,...,904149,4913,107717,90644,1046529,231141,49733,13104,7645804,21007358
서울,13131172,3581534,27647345,31228879,15150,4064,1918893,227077,497699,4399,...,163688,4395,11425,46225,20182,17656,132707,2875,1938107,46298158
세종,384903,299675,645424,945099,69469,16364,1502922,110211,70617,1324,...,26185,14319,33539,170366,79009,0,5132,2603,1588755,2918758
울산,1487143,489865,3649386,4139251,80221,20103,25883132,187738,943299,12286,...,169132,5053,381602,24165,2367150,1020610,4984,1626,25983456,31609850
인천,3856852,921748,7154416,8076164,142953,71529,12367816,641088,75895,639429,...,942801,7853,178502,1124564,612898,54225,360778,32538,12582298,24515313
전남,2284124,964024,5690659,6654683,3096126,73217,21453926,511361,160506,27998,...,66431,1061,149939,42399,72132,481592,14670,31932,24623269,33562076
전북,2326183,1096968,4910318,6007286,1415004,85300,12965875,1459217,731651,291729,...,159699,7240,130692,420005,859741,70980,16175,99003,14466179,22799647
제주,782601,301727,2308732,2610459,1364930,14019,241537,155987,3497,1524,...,1167,0,771,0,773,532,1743,743,1620486,5013545
충남,2691823,1089613,7164439,8254052,1928066,248313,37057955,1137035,269998,134109,...,611925,12208,428906,10953811,2526658,33766,53804,19725,39234334,50180209
충북,2027281,1267140,4804638,6071778,721131,139856,15883448,1152073,333846,51682,...,366871,23076,1125141,4103832,603349,82496,513501,46038,16744435,24843494